### PR TITLE
Adding tests files

### PR DESCRIPTION
**Pull request by TornaxO7**
I "fetched" two nds-examples from the [nds-examples](https://github.com/devkitPro/nds-examples) repository for the tests. Also added credits to their repository in the `README.md` file.

Currently only two tests are accepted, because the `build` function of the builder isn't implemented yet. I'll fix that in my next pull requests.

### CODE REVIEW

**Comment by TornaxO7** [comment]
Oh damn, this pull request also includes the changes from my previous pull request. Do you agree to merge the other one first?

**Comment by Roughsketch** [comment]
> 
> 
> Oh damn, this pull request also includes the changes from my previous pull request. Do you agree to merge the other one first?

The other one has been merged now, but for some reason github is not updating the diff. This happened with the previous PR as well, not sure what's going on.

**Comment by Roughsketch** [comment]
Does this PR have the files? I don't see them in the diff, but I do see the README reference.

**Comment by TornaxO7** [comment]
@Roughsketch you were right! They weren't included due to the `.gitignore` file. I fixed that now.

**Comment by TornaxO7** [comment]
I also changed the tests a little bit: Created two constant variables to these two `.nds` files.

**Comment by Roughsketch** [comment]
One last thing, can you remove the reference to mario_kart_ds in the parser test?

**Comment by TornaxO7** [comment]
Done

**Pull request merged**
